Bcpsdems 791 schema registry
sookeke/jps-pidp pull request #9
Opened 2022-12-15 01:13 UTC by leewrigh

2022-12-19 23:03 UTC, sookeke requested changes
I made some comment and please check there are some merge conflict file. 

Note there still secrets found on the pr and do not forget to revoke the secret after remediation

2022-12-19 23:03 UTC, sookeke commented on backend/service.edt/Kafka/ConsumerSetup.cs
> +            SaslMechanism = SaslMechanism.OAuthBearer,
@leewrigh  set consumer and producer cliendId for better event tracing
ClientId = Dns.GetHostName(),

2022-12-19 23:03 UTC, sookeke commented on backend/service.edt/ServiceEvents/SchemaAwareProducer.cs
> +            BasicAuthUserInfo = "registry-client-api:hPYOGgxHb8W1Wd4BAfkrvBF93IaBHI0d"
Please remove and revoke this secret asap

2023-01-05 21:11 UTC, leewrigh commented on backend/service.edt/Kafka/ConsumerSetup.cs
> +            SaslMechanism = SaslMechanism.OAuthBearer,
Done

2023-01-05 21:11 UTC, leewrigh commented on backend/service.edt/ServiceEvents/SchemaAwareProducer.cs
> +            BasicAuthUserInfo = "registry-client-api:hPYOGgxHb8W1Wd4BAfkrvBF93IaBHI0d"
Done

2023-01-05 22:38 UTC, sookeke approved these changes

2023-01-05 22:38 UTC, merged